import { CalendarClock, Sparkles, UserPlus } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import type { Challenge } from "@/types/challenge";
import type { Client } from "@/types/client";
import type { Collaborator } from "@/types/collaborator";

export function OpenChallengesDialog({ open, onOpenChange, challenges, units, currentUser, onAccept }: { open: boolean; onOpenChange: (open: boolean) => void; challenges: Challenge[]; units: Client[]; currentUser: Collaborator | null; onAccept: (id: string, collaboratorId: string) => Promise<boolean> }) {
  const unitNames = new Map(units.map((unit) => [unit.id, unit.name]));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Mural de desafios abertos</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Demandas internas sem responsável. Ao aceitar, o desafio entra nas suas entregas e segue para validação administrativa ao final.</p><div className="mt-2 space-y-3">{challenges.length === 0 ? <div className="border bg-muted/20 p-6 text-center text-sm text-muted-foreground">Nenhum desafio aberto no momento.</div> : challenges.map((challenge) => <article key={challenge.id} className="border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{challenge.title}</h3><p className="mt-1 text-xs text-muted-foreground">{challenge.clientId ? unitNames.get(challenge.clientId) ?? "Unidade interna" : "Geral da empresa"}</p></div><span className="bg-violet-100 px-2 py-1 text-[10px] font-semibold uppercase text-violet-800">Aberto</span></div><p className="mt-3 text-sm text-muted-foreground">{challenge.description || "Sem descrição adicional."}</p><div className="mt-3 border-l-2 border-primary/50 pl-3 text-sm"><span className="text-[10px] font-semibold uppercase text-muted-foreground">Condições</span><p>{challenge.successCriteria}</p></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><div className="flex flex-wrap gap-3"><span><CalendarClock className="mr-1 inline h-3.5 w-3.5" />{challenge.dueAt ? new Date(challenge.dueAt).toLocaleDateString("pt-BR") : "Sem prazo"}</span><span><Sparkles className="mr-1 inline h-3.5 w-3.5" />{challenge.rewardSuperstars} Super Estrelas</span>{challenge.penaltyStars > 0 && <span>Penalidade possível: {challenge.penaltyStars} estrelas</span>}</div>{currentUser ? <Button size="sm" onClick={() => void onAccept(challenge.id, currentUser.id)}><UserPlus className="mr-1 h-4 w-4" /> Aceitar desafio</Button> : <span>Selecione seu usuário para aceitar.</span>}</div></article>)}</div></DialogContent></Dialog>;
}
