import { useEffect, useState } from "react";
import { CalendarClock, Pencil, Trash2, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getChallengeElapsedDays } from "@/lib/challenge";
import { ChallengeConditionsEditor, ChallengeConditionsProgress } from "@/components/universe-ramos/ChallengeConditions";
import type { Collaborator } from "@/types/collaborator";
import type { Client } from "@/types/client";
import { CHALLENGE_STATUS_CONFIG, type Challenge, type ChallengeCompletionCondition, type ChallengeCompletionConditionInput, type ChallengeEditData } from "@/types/challenge";

export function UniverseChallengeDetailDialog({ challenge, open, onOpenChange, units, collaborators, conditions, onToggleCondition, canManage, onEdit, onDelete }: { challenge: Challenge | null; open: boolean; onOpenChange: (open: boolean) => void; units: Client[]; collaborators: Collaborator[]; conditions: ChallengeCompletionCondition[]; onToggleCondition?: (conditionId: string, completed: boolean) => void; canManage: boolean; onEdit: () => void; onDelete: () => void }) {
  if (!challenge) return null;
  const unit = units.find((item) => item.id === challenge.clientId);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><div className="flex items-start justify-between gap-3 pr-6"><div><DialogTitle>{challenge.title}</DialogTitle><p className="mt-1 text-sm text-muted-foreground">{unit?.name ?? "Geral da empresa"}</p></div><span className={`px-2 py-1 text-[10px] font-semibold uppercase ${CHALLENGE_STATUS_CONFIG[challenge.status].className}`}>{CHALLENGE_STATUS_CONFIG[challenge.status].label}</span></div></DialogHeader><div className="space-y-4 text-sm"><DetailSection label="Contexto e objetivo"><p className="whitespace-pre-wrap leading-6">{challenge.description || "Sem descrição adicional."}</p></DetailSection><DetailSection label="Condições de conclusão"><ChallengeConditionsProgress conditions={conditions} onToggle={onToggleCondition} /></DetailSection><div className="grid gap-3 sm:grid-cols-2"><Info label="Entregável esperado" value={challenge.expectedDeliverable || "Não definido"} /><Info label="Evidência necessária" value={challenge.evidenceRequirements || "Não definida"} /></div><div className="flex flex-wrap gap-3 border-t pt-3 text-xs text-muted-foreground"><span><CalendarClock className="mr-1 inline h-3.5 w-3.5" />Criado em {new Date(challenge.createdAt).toLocaleDateString("pt-BR")}</span><span>{getChallengeElapsedDays(challenge)} dias desde a criação</span><span><Users className="mr-1 inline h-3.5 w-3.5" />{collaborators.length ? "Consulte os responsáveis na tabela" : "Sem responsável"}</span></div></div>{canManage && <DialogFooter><Button variant="outline" onClick={onEdit}><Pencil className="h-4 w-4" />Editar</Button><Button variant="destructive" onClick={onDelete}><Trash2 className="h-4 w-4" />Excluir</Button></DialogFooter>}</DialogContent></Dialog>;
}

export function UniverseChallengeEditDialog({ challenge, open, onOpenChange, units, conditions: persistedConditions = [], onSave }: { challenge: Challenge | null; open: boolean; onOpenChange: (open: boolean) => void; units: Client[]; conditions?: ChallengeCompletionCondition[]; onSave: (challengeId: string, data: ChallengeEditData) => Promise<boolean> }) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [conditions, setConditions] = useState<ChallengeCompletionConditionInput[]>([]); const [deliverable, setDeliverable] = useState(""); const [evidence, setEvidence] = useState(""); const [unitId, setUnitId] = useState(""); const [dueAt, setDueAt] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!challenge) return; setTitle(challenge.title); setDescription(challenge.description ?? ""); setConditions(persistedConditions.length ? persistedConditions.map((condition) => ({ title: condition.title, isRequired: condition.isRequired })) : challenge.successCriteria.split("\n").filter(Boolean).map((title) => ({ title, isRequired: true }))); setDeliverable(challenge.expectedDeliverable ?? ""); setEvidence(challenge.evidenceRequirements ?? ""); setUnitId(challenge.clientId ?? ""); setDueAt(challenge.dueAt ? challenge.dueAt.slice(0, 16) : ""); }, [challenge, persistedConditions]);
  if (!challenge) return null;
  const submit = async () => { const validConditions = conditions.filter((condition) => condition.title.trim()); if (!title.trim() || !validConditions.length) return; setSaving(true); const done = await onSave(challenge.id, { title: title.trim(), description: description.trim() || undefined, successCriteria: validConditions.map((condition) => condition.title.trim()).join("\n"), conditions: validConditions, expectedDeliverable: deliverable.trim() || undefined, evidenceRequirements: evidence.trim() || undefined, clientId: unitId || null, kind: challenge.kind, dueAt: dueAt ? new Date(dueAt).toISOString() : null }); setSaving(false); if (done) onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Editar desafio</DialogTitle></DialogHeader><div className="grid gap-4"><Field label="Título"><Input value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="Origem"><select className="h-10 w-full border bg-background px-3 text-sm" value={unitId} onChange={(event) => setUnitId(event.target.value)}><option value="">Geral da empresa</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></Field><Field label="Descrição e contexto"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Field label="Condições de conclusão"><ChallengeConditionsEditor conditions={conditions} onChange={setConditions} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Entregável esperado"><Textarea value={deliverable} onChange={(event) => setDeliverable(event.target.value)} /></Field><Field label="Evidência necessária"><Textarea value={evidence} onChange={(event) => setEvidence(event.target.value)} /></Field></div><Field label="Prazo (opcional)"><Input type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={!title.trim() || !conditions.some((condition) => condition.title.trim()) || saving} onClick={() => void submit()}>{saving ? "Salvando..." : "Salvar alterações"}</Button></DialogFooter></DialogContent></Dialog>;
}

function DetailSection({ label, children }: { label: string; children: React.ReactNode }) { return <section className="border bg-muted/20 p-4"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p>{children}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <section className="border bg-card p-4"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 whitespace-pre-wrap leading-6">{value}</p></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm"><span className="font-medium">{label}</span>{children}</label>; }
